org.gradle.jvmargs  = -Xmx2G
org.gradle.parallel = true
org.gradle.caching = true
org.gradle.configuration-cache = true
org.gradle.configureondemand = true
org.gradle.continue = true
#org.gradle.warning.mode = all

# Plugin versions
plugins.foojay.version = 1.0.0
plugins.loom.version = 1.17.16
plugins.moddev.version = 2.0.142

# Shared
project_version = 1.0.0
project_group = l1am.leggen
project_id = leggen
project_name = Leggen
project_owner = Liam Baile
project_license = ARR

minecraft_version = 26.2

fabric_loader_version = 0.19.3
fabric_api_version = 0.156.0+26.2

neo_form_version = 26.2-1
neoforge_version = 26.2.0.32-beta
neoforge_loader_minimum = 4
