plugins {
    id 'java-library'
    id 'maven-publish'
}

group = project_group
version = project_version

base {
    archivesName = "${project_id}-${project.name}-${minecraft_version}"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
    withSourcesJar()
    withJavadocJar()
}

jar {

    manifest {
        attributes([
                'Specification-Title'   : project_name,
                'Specification-Vendor'  : project_owner,
                'Specification-Version' : project.jar.archiveVersion,
                'Implementation-Title'  : project.name,
                'Implementation-Version': project.jar.archiveVersion,
                'Implementation-Vendor' : project_owner,
                'Built-On-Minecraft'    : minecraft_version
        ])
    }
}

processResources {
    var expandProps = [
            'version'                      : version,
            'group'                        : project.group,
            'minecraft_version'            : minecraft_version,
            'fabric_version'               : fabric_api_version,
            'fabric_loader_version'        : fabric_loader_version,
            'mod_name'                     : project_name,
            'mod_author'                   : project_owner,
            'mod_id'                       : project_id,
            'license'                      : project_license,
            'description'                  : "",
            'neoforge_version'             : neoforge_version,
            'neoforge_loader_version_range': "[${neoforge_loader_minimum},)",
            'credits'                      : "",
            'java_version'                 : "25"
    ]

    var jsonExpandProps = expandProps.collectEntries {
        key, value -> [(key): value instanceof String ? value.replace('\n', '\\\\n') : value]
    }

    filesMatching(['META-INF/mods.toml', 'META-INF/neoforge.mods.toml']) {
        expand expandProps
    }

    filesMatching(['pack.mcmeta', 'fabric.mod.json', '*.mixins.json']) {
        expand jsonExpandProps
    }

    inputs.properties(expandProps)
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifactId base.archivesName.get()
            from components.java
        }
    }
    repositories {
        maven {
            url System.getenv('local_maven_url')
        }
    }
}
